import axios from 'axios'

export enum SURAH{
    "Al-Fatihah" = 1,
    "Al-Baqarah" = 2,
    "Ali Imran" = 3,
    "An Nisa" = 4,
    "Al-Maidah" = 5,
    "Al-An'am" = 6,
    "Al-A'raf" = 7,
    "Al-Anfal" = 8,
    "At-Tauba" = 9,
    "Yunus" = 10,
    "Hud" = 11,
    "Yusuf" = 12,
    "Ar-Ra'd" = 13,
    "Ibrahim" = 14,
    "Al-Hijr" = 15,
    "An-Nahl" = 16,
    "Al-Isra'" = 17,
    "Al-Kahf" = 18,
    "Maryam" = 19,
    "Ta Ha" = 20,
    "Al-Anbiya" = 21, 
    "Al-Hajj" = 22, 
    "Al-Mu'minun" = 23, 
    "An-Nur" = 24,
    "Al-Furqan" = 25,
    "Asy-Syu'ara'" = 26,
    "An-Naml" = 27,
    "Al-Qasas" = 28,
    "Al-'Ankabut" = 29,
    "Ar-Rum" = 30,
    "Luqman" = 31,
    "As-Sajdah" = 32,
    "Al-Ahzab" = 33,
    "Saba'" = 34,
    "Fatir" = 35,
    "Ya Sin" = 36,
    "As-Saffat" = 37,
    "Sad" = 38,
    "Az-Zumar" = 39,
    "Ghafir" = 40,
    "Fussilat" = 41,
    "Asy-Syura" = 42,
    "Az-Zukhruf" = 43,
    "Ad-Dukhan" = 44,
    "Al-Jasiyah" = 45,
    "Al-Ahqaf" = 46,
    "Muhammad" = 47,
    "Al-Fath" = 48,
    "Al-Hujurat" = 49,
    "Qaf" = 50,
    "Az-Zariyat" = 51,
    "At-Tur" = 52,
    "An-Najm" = 53,
    "Al-Qamar" = 54,
    "Ar-Rahman" = 55,
    "Al-Waqi'ah" = 56,
    "Al-Hadid" = 57,
    "Al-Mujadilah" = 58, 
    "Al-Hasyr" = 59,
    "Al-Mumtahanah" =  60, 
    "As-Saff" = 61,
    "Al-Jumu'ah" = 62,
    "Al-Munafiqun" = 63,
    "At-Tagabun" = 64,
    "At-Talaq" = 65,
    "At-Tahrim" = 66,
    "Al-Mulk" = 67,
    "Al-Qalam" = 68,
    "Al-Haqqah" = 69,
    "Al-Ma'arij" = 70,
    "Nuh" = 71,
    "Al-Jinn" = 72, 
    "Al-Muzzammil" = 73, 
    "Al-Muddassir" = 74,
    "Al-Qiyamah" = 75,
    "Al-Insan" = 76,
    "Al-Mursalat" = 77,
    "An-Naba'" = 78,
    "An-Nazi'at" = 79,
    "'Abasa" = 80,
    "At-Takwir" = 81,
    "Al-Infitar" = 82,
    "Al-Tatfif" = 83,
    "Al-Insyiqaq" = 84,
    "Al-Buruj" = 85,
    "At-Tariq" = 86,
    "Al-A'la" = 87,
    "Al-Gasyiyah" = 88, 
    "Al-Fajr" = 89,
    "Al-Balad" = 90,
    "Asy-Syams" = 91,
    "Al-Lail" = 92,
    "Ad-Duha" = 93,
    "Al-Insyirah" = 94, 
    "At-Tin" = 95,
    "Al-'Alaq" = 96,
    "Al-Qadr" = 97,
    "Al-Bayyinah" = 98, 
    "Az-Zalzalah" = 99,
    "Al-'Adiyat" = 100,
    "Al-Qari'ah" = 101,
    "At-Takasur" = 102,
    "Al-'Asr" = 103,
    "Al-Humazah" = 104,
    "Al-Fil" = 105,
    "Quraisy" = 106,
    "Al-Ma'un" = 107,
    "Al-Kausar" = 108,
    "Al-Kafirun" = 109,
    "An-Nasr" = 110,
    "Al-Lahab" = 111,
    "Al-Ikhlas" = 112,
    "Al-Falaq" = 113,
    "An-Nas" = 114
}
interface IProps {
    surat: number
    ayat?: number,
    
}
export const getQuran = (params: IProps) : string =>  {
    let result = '/quran'
    let param: keyof typeof params
    for(param in params){
        result+= `/${params[param]}`
    }
    return result
}

export default axios.create({
    baseURL: 'https://quran-endpoint.vercel.app',
})